# Generated by Django 3.2.7 on 2022-03-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220321_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='added_to_google_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
