# Generated by Django 3.2.7 on 2022-04-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted'), ('declined', 'declined'), ('pending', 'pending')], max_length=8),
        ),
    ]
