version: "3.8"
services:
  api_django:
    container_name: api_django
    build:
      context: ./_dockerfiles/backend/
    ports:
      - "8080:5000"
    environment:
      DATABASE: postgres
      HOST_ADDRESS: postgres:5432
      DB_USER: DEVSECOPS
      DB_PASSWORD: PGDCLOUD
      STATSD_HOST: 44.199.254.34
      TYPE: dev
    depends_on:
      - db
    entrypoint: /code/entrypoint.sh
    networks:
      - winterfun_network

  db:
    container_name: postgres
    build:
      context: ./_dockerfiles/postgres
    image: wislan/docker_winterfun:winterfun_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: DEVSECOPS
      POSTGRES_PASSWORD: PGDCLOUD
      POSTGRES_HOSTNAME: localhost:5432
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - winterfun_network

  nginx:
    restart: always
    depends_on:
      - api_django
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    build:
      context: ./_dockerfiles/nginx
    ports:
      - "80:80"
    networks:
      - winterfun_network

networks:
    winterfun_network:
        driver: bridge
volumes:
    postgres_db_volume:
        driver: local
    static_volume:
    media_volume:
