version: '3.2'

services:
  elasticsearch:
    restart: always
    build:
      context: ./_dockerfiles/elasticsearch
      args:
        ELK_VERSION: 7.16.3
    volumes:
      - ./_dockerfiles/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  kibana:
    restart: always
    build:
      context: ./_dockerfiles/kibana
      args:
        ELK_VERSION: 7.16.3
    volumes:
      - ./_dockerfiles/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    restart: always
    user: root
    container_name: filebeat
    image: wislan/docker_winterfun:winterfun_filebeat
    volumes:
      - ./_dockerfiles/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ELASTICSEARCH_HOST=100.26.242.218
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - KIBANA_HOST=100.26.242.218
      - ELASTIC_INDEX=winterfun-elastic-search-server
    command: [ "--strict.perms=false" ]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch: