# Generated by Django 3.2.7 on 2022-03-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20220319_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sender',
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
