name: "Destroy Infra: x21126151_Wislan_Lima"

on:
  workflow_dispatch
  
jobs:
  terraform:
    name: "Destroying Infrastructure"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'x21126151_Wislan_Lima'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -diff

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Destroy
        id: destroy
        env:
          TF_VAR_pvt_key: ${{ secrets.AWS_PVT_KEY }}
        run: terraform destroy -auto-approve
