name: "1 Build_Docker and Push_Docker: WinterFun"

on:
  workflow_dispatch:

  workflow_call:
    secrets:
      DOCKER_UN:
        required: true
      DOCKER_PWD:
        required: true
  #push:
  #  branches:
  #    - 'main'

jobs:
  BuildStart:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Start of Build'
  Backend:
    runs-on: ubuntu-latest
    needs: BuildStart
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_UN }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push Backend
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./_dockerfiles/backend
          tags: wislan/docker_winterfun:winterfun_backend
  Postgres:
    runs-on: ubuntu-latest
    needs: BuildStart
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_UN }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push Postgres
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./_dockerfiles/postgres
          tags: wislan/docker_winterfun:winterfun_postgres
  Telegraf:
    runs-on: ubuntu-latest
    needs: BuildStart
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_UN }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push Telegraf
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./_dockerfiles/telegraf
          tags: wislan/docker_winterfun:winterfun_telegraf
  Filebeat:
    runs-on: ubuntu-latest
    needs: BuildStart
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_UN }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push FileBeat
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./_dockerfiles/filebeat
          tags: wislan/docker_winterfun:winterfun_filebeat
  Redis:
    runs-on: ubuntu-latest
    needs: BuildStart
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_UN }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push Redis
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./_dockerfiles/redis
          tags: wislan/docker_winterfun:winterfun_redis
  PushComplete:
    runs-on: ubuntu-latest
    needs: [Filebeat, Telegraf, Postgres, Backend, Redis]
    steps:
      - run: echo 'End of Push'
